"""Initial migration

Revision ID: 7d4b7f6991af
Revises: 
Create Date: 2024-12-05 15:19:36.944629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4b7f6991af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TABLE IF NOT EXISTS admins (
        id BIGSERIAL PRIMARY KEY,
        state BOOLEAN NOT NULL
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS chat_links (
        id BIGSERIAL PRIMARY KEY,
        text VARCHAR NOT NULL,
        link VARCHAR NOT NULL,
        priority INTEGER NOT NULL,
        UNIQUE (link),
        UNIQUE (text)
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS chats (
        id BIGINT NOT NULL,
        welcome_message VARCHAR,
        time_delete INTEGER NOT NULL,
        is_welcome_enabled BOOLEAN NOT NULL,
        is_captcha_enabled INTEGER NOT NULL,
        PRIMARY KEY (id)
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS messages (
        id BIGSERIAL PRIMARY KEY,
        chat_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        message_id BIGINT NOT NULL,
        message VARCHAR,
        message_info JSON NOT NULL,
        timestamp TIMESTAMP NOT NULL,
        spam BOOLEAN NOT NULL
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id BIGSERIAL PRIMARY KEY,
        verify BOOLEAN NOT NULL,
        blocked BOOLEAN NOT NULL
    )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('chats')
    op.drop_table('chat_links')
    op.drop_table('admins')
    # ### end Alembic commands ###
